### ISSUE TITLE
linux & mac 下运行 start.sh 报错

### ISSUE THREAD

**Issue by mimicode** [enilu/database-doc-generator#3]
![image](https://user-images.githubusercontent.com/8034609/50808377-3bde5180-1339-11e9-9b7b-bc8112f3ad96.png)

**Comment by mimicode** [comment]
`[root@8fcffbe0a4cf bin]# java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)`

**Comment by enilu** [comment]
start.sh编码问题，最新版已经修复 https://github.com/enilu/database-doc-generator/releases/download/1.2.0/database-doc-generator-1.2.0.zip
